server:
  port: 8085

spring:
  application:
    name: publication-service
  datasource:
    url: jdbc:mysql://localhost:3306/publication_db
    username: root
    password: tu_clave
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true